services:
  - name: staff-management
    type: web
    runtime: docker
    plan: free
    repo: https://github.com/Sumntpathak/Staff-Management.git
    dockerfilePath: Dockerfile

    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:h2:mem:testdb
      - key: SPRING_DATASOURCE_DRIVER_CLASS_NAME
        value: org.h2.Driver
      - key: SPRING_DATASOURCE_USERNAME
        value: sa
      - key: SPRING_DATASOURCE_PASSWORD
        value:
      - key: SPRING_JPA_DATABASE_PLATFORM
        value: org.hibernate.dialect.H2Dialect
